language: cpp

compiler:
  - gcc
  - clang
  
env:
  matrix:
    - BUILD_SYSTEM=cmake
    
install:
  - sudo add-apt-repository --yes ppa:smspillaz/cmake-2.8.12
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  
before_script:
  - mkdir build
  - cd build
  
script:
  - cmake ..
  - cmake --build . --target install

os:
  - linux